---
AllCops:
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - bin/**/*
    - doc/**/*
    - db/migrate/**/*
    - db/seeds.rb
    - features/**/*.rb
  Include:
    - "**/Rakefile"
    - "**/config.ru"
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/ParameterLists:
  Max: 6
Rails:
  Enabled: true
Style/RaiseArgs:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

